GET http://localhost:30026/players/
###
GET http://localhost:30024/players/1/
###
POST http://localhost:30024/players/

Content-Type:application/json
###

PUT http://localhost:30026/players/2/

Content-Type:application/json

{
"player_name":"Ram"

}

###
GET http://localhost:30024/matches/18/
###

GET http://localhost:30026/players/1/matches/

###

GET http://localhost:30026/matches/4/players/

###


GET http://localhost:30026/players/3/playerScores/
